#!/bin/bash
LIBRESPOT_ZEROCONF_PORT=45305
LIBRESPOT_INITIAL_VOLUME=60
LIBRESPOT_DEVICE=SpotCon_in
LIBRESPOT_ENABLE_VOLUME_NORMALISATION=on
LIBRESPOT_DISABLE_AUDIO_CACHE=
LIBRESPOT_AUTOPLAY=off
LIBRESPOT_SYSTEM_CACHE=/home/pi/Oradio3
LIBRESPOT_BACKEND=alsa
LIBRESPOT_NAME=Oradio-LSP
LIBRESPOT_VERBOSE=on
LIBRESPOT_ONEVENT=/home/pi/Oradio3/Python/librespot_event_handler.py
LIBRESPOT_DEVICE_TYPE=speaker

export LIBRESPOT_ZEROCONF_PORT
export LIBRESPOT_INITIAL_VOLUME
export LIBRESPOT_DEVICE
export LIBRESPOT_ENABLE_VOLUME_NORMALISATION
export LIBRESPOT_DISABLE_AUDIO_CACHE
export LIBRESPOT_AUTOPLAY
export LIBRESPOT_SYSTEM_CACHE
export LIBRESPOT_BACKEND
export LIBRESPOT_NAME
export LIBRESPOT_VERBOSE
export LIBRESPOT_ONEVENT
export LIBRESPOT_DEVICE_TYPE

/usr/bin/librespot  --bitrate 320 --backend pipe --device /home/pi/spotify/librespot-pipe
