no-video
idle=no
input-ipc-server=/home/pi/spotify/mpv-socket
log-file=/home/pi/logging/mpv.log
msg-level=all-v
demuxer=rawaudio
demuxer-rawaudio-format=s16le
demuxer-rawaudio-rate=44100
demuxer-rawaudio-channels=2
audio-device=alsa/SpotCon_in
