#!/bin/bash
#
#  ####   #####     ##    #####      #     ####
# #    #  #    #   #  #   #    #     #    #    #
# #    #  #    #  #    #  #    #     #    #    #
# #    #  #####   ######  #    #     #    #    #
# #    #  #   #   #    #  #    #     #    #    #
#  ####   #    #  #    #  #####      #     ####
#
# Created on April 17, 2025
# @author:        Henk Stevens & Olaf Mastenbroek & Onno Janssen
# @copyright:     Stichting Oradio
# @license:       GNU General Public License (GPL)
# @organization:  Stichting Oradio
# @version:       1
# @email:         info@stichtingoradio.nl
# @status:        Development

########## INITIALIZE BEGIN ##########

# Color definitions
RED='\033[1;31m'
YELLOW='\033[1;93m'
GREEN='\033[1;32m'
NC='\033[0m'

# Hardware version info
if [ -f /var/log/oradio_hw_version.log ]; then
	echo "Oradio hardware version info:"
	cat /var/log/oradio_hw_version.log
else
    echo -e "${YELLOW}No hardware version info found${NC}"
fi

# Software version info
if [ -f /var/log/oradio_sw_version.log ]; then
	echo "Oradio software version info:"
	cat /var/log/oradio_sw_version.log
else
    echo -e "${YELLOW}No software version info found${NC}"
fi
