# https://pipewire.org/
# https://wiki.debian.org/PipeWire
# https://pipewire.pages.freedesktop.org/wireplumber/index.html
wireplumber.profiles = {
  main = {
    # Disable video profile
    hardware.video-capture = disabled

    # Disable Bluetooth profile
    hardware.bluetooth = disabled
  }
}