### Oradio MPD settings overriding /etc/mpd.conf defaults ###

# Effectively set the connection timeout to infinite
connection_timeout "31536000"

# Set audio files directory to USB
music_directory		"/media/oradio/Muziek"

# Set playlist directory to USB
playlist_directory	"/media/oradio/Speellijsten"

# set MPD database location
db_file				"/home/pi/.config/mpd/tag_cache"

# Set MPD logfile to Oradio logging directory
#log_file			"/home/pi/Oradio3/logging/mpd.log"

# Suppress all messages below the given threshold.  Use "verbose" for troubleshooting
# Available setting arguments are "notice", "info", "verbose", "warning" and "error"
#log_level			"notice"

# Put MPD into pause mode instead of starting playback after startup
restore_paused		"yes"

# Define a list of tag types extracted during the audio file discovery process
metadata_to_use	"artist,title"

# Set loudness of each song within a collection of songs to be consistent
replaygain			"track"

# Sets the pre-amp used for files that have ReplayGain tags
replaygain_preamp	"6"

# Sets the pre-amp used for files that do NOT have ReplayGain tags
replaygain_missing_preamp	"-2"

# Disable ReplayGain limiting
replaygain_limit	"no"

# Correctly display file or directory names for our locale
filesystem_charset	"UTF-8"

# Prevent "plugin unavailable" warning
decoder {
    plugin "wildmidi"
    enabled "no"
}

# Oradio audio output
audio_output {
    type            "pipewire"
    name            "MPD Output"
}
