#!/usr/bin/env bash
#
#  ####   #####     ##    #####      #     ####
# #    #  #    #   #  #   #    #     #    #    #
# #    #  #    #  #    #  #    #     #    #    #
# #    #  #####   ######  #    #     #    #    #
# #    #  #   #   #    #  #    #     #    #    #
#  ####   #    #  #    #  #####      #     ####
#
# Created on September 7, 2026
# @author:        Henk Stevens & Olaf Mastenbroek & Onno Janssen
# @copyright:     Stichting Oradio
# @license:       GNU General Public License (GPL)
# @organization:  Stichting Oradio
# @version:       2
# @email:         info@stichtingoradio.nl
# @status:        Development
# @Reference:
#	https://ffmpeg.org/ffmpeg-filters.html#loudnorm
#	https://ffmpeg.org/ffmpeg-filters.html#silenceremove
#	https://tech.ebu.ch/publications/r128/
# @Purpose:
#	Converts every MP3 in a folder to Oradio system sound WAV files
#	- decodes to 16 kHz, signed 16-bit, mono PCM WAV
#	- trims leading/trailing silence
#	- normalizes to -19 LUFS loudness (two pass, EBU R128)
#	- names each output after its input, with .mp3 replaced by .wav
#	- offers a simple playback menu (`aplay`)
#
#	Companion to tts_messages_generator.sh: same output format, but for audio
#	generated by hand in the ElevenLabs web interface instead of through the API
#
#	ffmpeg does all three audio steps in one filter chain, so a file is read
#	twice and written once, with no intermediate files. Version 1 of this script
#	spent nine processes and two temp files per file: ffmpeg to decode, sox to
#	trim, ffmpeg to measure, five jq calls to read five fields out of one JSON
#	document, and ffmpeg to apply. sox and jq are no longer needed at all
#
# @Usage:
#	./mp3_to_wav_converter.sh INPUT_DIR OUTPUT_DIR
#	./mp3_to_wav_converter.sh --help

##### Initialize #####################

# Stop on errors (-e), catch unset variables (-u), catch failures in any part of a pipeline (-o pipefail)
set -euo pipefail

# Color definitions
RED='\033[1;31m'
YELLOW='\033[1;93m'
GREEN='\033[1;32m'
NC='\033[0m'

#---------- Ensure using bash ----------

# The script uses bash constructs
if [ -z "${BASH:-}" ]; then
	echo -e "${RED}This script requires bash${NC}"
	exit 1
fi

#---------- Config ----------

# Target WAV format, matching what the Oradio expects and what aplay handles
SAMPLE_RATE=16000
BIT_DEPTH=16
CHANNELS=1

# Loudness normalization parameters (EBU R128)
# LOUDNESS_TARGET: integrated loudness in LUFS, -23 is the EBU broadcast
#                  standard and -16 the usual value for mono speech
# TRUE_PEAK_MAX:   ceiling in dBTP. Kept below 0 to leave room for intersample
#                  peaks that only appear after the DAC reconstructs the signal
# LOUDNESS_RANGE:  allowed spread between soft and loud parts, in LU
#
# -19 rather than -16, because the target and the peak ceiling fight each other.
# Raising a file to -16 LUFS with one constant gain would push the loudest
# syllable of some prompts past TRUE_PEAK_MAX, so loudnorm gives back just
# enough gain to stay under the ceiling and the file lands short of the target.
# Measured on the ElevenLabs 'Roos' set: at -16 the files ended up spread over
# -15.8 to -18.4 LUFS, which is exactly the mismatch this script exists to
# remove. At -19 every file reaches the target within 0.2 LU
#
# If the whole set sounds too soft on the Oradio speaker, do not chase a higher
# target here: raise the playback volume instead. Aiming higher only brings the
# spread back
LOUDNESS_TARGET="-19"
TRUE_PEAK_MAX="-1.5"
LOUDNESS_RANGE="11"

# Silence detection parameters
# These are ffmpeg's, not SoX's, and they do not carry the same meaning as the
# ones in tts_messages_generator.sh
#
# SILENCE_THRESHOLD: level below which audio counts as silence. Raise it (-40dB)
#                    to trim more, lower it (-60dB) to trim less. Measured
#                    against SoX on the ElevenLabs 'Roos' set, -50dB with RMS
#                    detection lands within a few hundredths of a second of what
#                    'silence 1 0.3 0.1%' produced. Peak detection is far too
#                    conservative here: one stray sample above the threshold
#                    counts as speech, and the recordings have a noise floor
# SILENCE_DURATION:  how long the audio must stay above the threshold before
#                    trimming stops. 0 cuts at the first window that rises above
#                    it, which is what short spoken prompts want
# SILENCE_KEEP:      seconds of silence to leave at each end
#
# SILENCE_KEEP is not cosmetic. EBU R128 measures in blocks of 400 ms, so a file
# shorter than a single block has no measurable loudness at all and loudnorm
# reports -inf. Trimmed flush, 'drie' came out at 0.35 s and could not be
# normalized. The 0.1 s left at each end puts the short prompts back over that
# floor, and it also keeps a prompt from starting on an audible click
SILENCE_THRESHOLD="-50dB"
SILENCE_DURATION=0
SILENCE_KEEP=0.1

# Trim both ends, then measure or correct the loudness of what is left. Built
# once here instead of per file, and shared by both passes so the second pass
# cannot normalize different audio than the first pass measured
#
# areverse buffers the whole stream, which is why the trailing silence is
# handled by reversing twice rather than by stop_periods: it keeps the pauses
# inside a sentence intact, and system prompts are short enough that buffering
# them costs nothing
TRIM_FILTER="silenceremove=start_periods=1:start_duration=${SILENCE_DURATION}:start_silence=${SILENCE_KEEP}:start_threshold=${SILENCE_THRESHOLD}:detection=rms"
TRIM_FILTER="${TRIM_FILTER},areverse,${TRIM_FILTER},areverse"

#---------- Usage ----------

usage() {
	cat <<EOF
Usage: ${0##*/} INPUT_DIR OUTPUT_DIR
       ${0##*/} -h | --help

Converts every MP3 in INPUT_DIR to an Oradio system sound WAV in OUTPUT_DIR.

Arguments:
  INPUT_DIR    Folder to read the MP3 files from. Must exist and hold at least
               one .mp3. Only this folder is read, subfolders are ignored
  OUTPUT_DIR   Folder to write the WAV files to. Created when it does not exist.
               Existing WAV files are kept unless you confirm overwriting

Options:
  -h, --help   Show this text and exit

Each file is decoded to ${SAMPLE_RATE} Hz, ${BIT_DEPTH} bit, $( [ "$CHANNELS" -eq 1 ] && echo mono || echo "$CHANNELS channel" ) PCM, has the silence at
both ends trimmed, and is normalized to ${LOUDNESS_TARGET} LUFS with a ${TRUE_PEAK_MAX} dBTP ceiling,
so every message plays back at the same loudness.

Each output file is named after its input, with the extension replaced:
recording.mp3 becomes recording.wav. Name the MP3 files the way the Oradio
expects them before converting.

Example:
  ${0##*/} ~/Oradio3/tts_mp3 ~/Oradio3/tts_sounds
EOF
}

#---------- Parse arguments ----------

# Handled before the package check, so --help stays instant and does not trigger
# an apt run on a Lite image
case "${1:-}" in
	-h|--help)
		usage
		exit 0
		;;
esac

if [ "$#" -ne 2 ]; then
	echo -e "${RED}Expected two arguments: an input and an output folder${NC}" >&2
	echo "" >&2
	usage >&2
	exit 1
fi

INPUT_DIR="$1"
OUTPUT_DIR="$2"

#---------- Locate the helper scripts ----------

# pkg-helper.sh sits next to this script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#---------- Ensure required packages are installed and up to date ----------

# ffmpeg decodes, resamples, trims and normalizes, so it is the only audio tool
# needed. SoX cannot do the loudness part at all - its 'gain -n' is peak
# normalization - and once ffmpeg is installed for that, letting it do the
# trimming too saves a process, a temp file and a second set of parameters to
# keep in sync
#
# jq is not in this list on purpose: the measuring pass prints one small JSON
# document with a fixed set of keys, which the read loop below parses with bash
# builtins
#
# alsa-utils is for aplay, used by the playback menu at the end
bash "$SCRIPT_DIR/pkg-helper.sh" ffmpeg alsa-utils

#---------- Check input folder ----------

if [ ! -d "$INPUT_DIR" ]; then
	echo -e "${RED}Input folder does not exist: $INPUT_DIR${NC}" >&2
	exit 1
fi

# A glob instead of 'find | sort': bash expands it already sorted, nocaseglob
# picks up .MP3 as well, and nullglob makes an empty folder yield an empty array
# rather than the literal pattern
shopt -s nullglob nocaseglob
MP3_FILES=("$INPUT_DIR"/*.mp3)
shopt -u nullglob nocaseglob

if [ "${#MP3_FILES[@]}" -eq 0 ]; then
	echo -e "${RED}No MP3 files found in: $INPUT_DIR${NC}" >&2
	exit 1
fi

echo "Found ${#MP3_FILES[@]} MP3 file(s) in $INPUT_DIR"

mkdir -p "$OUTPUT_DIR"

# By default, existing WAV files are skipped
# To reconvert only one file, delete it: rm -f OUTPUT_DIR/<file>.wav
FORCE_REGENERATE=false

# Prompt for overwrite or check only
read -r -p "Overwrite existing sound files[y/N]: " answer
if [[ "$answer" =~ ^[Yy]$ ]]; then
	FORCE_REGENERATE=true
	echo -e "${YELLOW}Existing system sound files will be overwritten${NC}"
fi

#---------- Functions ----------

convert() {
	# Decodes, trims and loudness normalizes one MP3 in two ffmpeg passes
	#
	# Two passes rather than one because single pass loudnorm adapts while it
	# runs, which changes the dynamics of the recording. Fed the measurements up
	# front with linear=true it applies one constant gain instead, leaving the
	# recording intact and only moving its level
	local src="$1"
	local dst="$2"

	local settings="I=${LOUDNESS_TARGET}:TP=${TRUE_PEAK_MAX}:LRA=${LOUDNESS_RANGE}"

	# Pass 1: trim and measure, decoding straight from the MP3 and discarding
	# the audio. Measuring after the trim matters: a long lead-in would drag the
	# integrated loudness down and the correction with it
	local in_i="" in_tp="" in_lra="" in_thresh="" offset=""
	local key value

	# loudnorm prints its JSON on stderr, mixed in with the ffmpeg log. Rather
	# than isolating the document and handing it to jq, pick the five fields out
	# of the stream directly - a JSON parser is a lot of machinery for five
	# numbers on five predictable lines
	while IFS= read -r line; do
		[[ "$line" =~ \"([a-z_]+)\"[[:space:]]*:[[:space:]]*\"([^\"]+)\" ]] || continue
		key="${BASH_REMATCH[1]}"
		value="${BASH_REMATCH[2]}"
		case "$key" in
			input_i)      in_i="$value" ;;
			input_tp)     in_tp="$value" ;;
			input_lra)    in_lra="$value" ;;
			input_thresh) in_thresh="$value" ;;
			target_offset) offset="$value" ;;
		esac
	done < <(ffmpeg -hide_banner -nostdin -i "$src" \
		-af "${TRIM_FILTER},loudnorm=${settings}:print_format=json" \
		-f null - 2>&1)

	if [ -z "$in_i" ] || [ -z "$offset" ]; then
		echo -e "${RED}Failed to measure loudness of ${src##*/}${NC}" >&2
		return 1
	fi

	# A file that is silent, or so short that the gate never opens, measures as
	# -inf and cannot be normalized. Report it instead of writing a file that is
	# either unchanged or amplified to noise
	if [[ "$in_i" == "-inf" ]]; then
		echo -e "${YELLOW}No measurable loudness, too short after trimming: ${src##*/}" >&2
		echo -e "Raise SILENCE_KEEP above ${SILENCE_KEEP} to clear the 400 ms R128 block${NC}" >&2
		return 1
	fi

	# Pass 2: trim and correct, writing the finished WAV
	# The explicit -ar matters: loudnorm resamples to 192 kHz internally, and
	# without it that is also what ends up in the output file
	if ! ffmpeg -v error -nostdin -y -i "$src" \
			-af "${TRIM_FILTER},loudnorm=${settings}:measured_I=${in_i}:measured_TP=${in_tp}:measured_LRA=${in_lra}:measured_thresh=${in_thresh}:offset=${offset}:linear=true" \
			-ar "$SAMPLE_RATE" -ac "$CHANNELS" -c:a "pcm_s${BIT_DEPTH}le" \
			"$dst"; then
		echo -e "${RED}Failed to convert ${src##*/}${NC}" >&2
		rm -f "$dst"
		return 1
	fi

	echo "Loudness: ${in_i} LUFS → ${LOUDNESS_TARGET} LUFS (peak was ${in_tp} dBTP)"
	return 0
}

menu_playback() {
	local files=("$@")
	echo ""
	echo "--- Play --- (number or '0' to quit)"
	while true; do
		local i=1
		for f in "${files[@]}"; do
			echo "[$i] ${f##*/}"
			((i++))
		done
		read -rp "Choice: " choice
		[[ "$choice" == "0" ]] && break
		if [[ "$choice" =~ ^[0-9]+$ && "$choice" -ge 1 && "$choice" -le "${#files[@]}" ]]; then
			aplay -q "${files[$((choice-1))]}"
		else
			echo -e "${YELLOW}Invalid choice${NC}"
		fi
	done
}

#---------- Main ----------

converted=()
skipped=()
failed=()

for src in "${MP3_FILES[@]}"; do
	src_base="${src##*/}"

	# Output name is the input name with its extension swapped for .wav.
	# '%.*' strips the last dot and everything after it, so .MP3 picked up by
	# nocaseglob also lands on a lower case .wav
	fname="${src_base%.*}.wav"
	path="$OUTPUT_DIR/$fname"

	if [[ -f "$path" && -s "$path" && "$FORCE_REGENERATE" = "false" ]]; then
		echo "Already exists, skip: $fname"
		skipped+=("$path")
		continue
	fi

	echo ""
	echo "Convert $src_base → $fname"

	if convert "$src" "$path"; then
		converted+=("$path")
	else
		failed+=("$src")
	fi
done

echo ""
echo -e "${GREEN}${#converted[@]} file(s) converted.${NC}"
echo -e "${YELLOW}${#skipped[@]} file(s) skipped.${NC}"
if [ "${#failed[@]}" -gt 0 ]; then
	echo -e "${RED}${#failed[@]} file(s) failed:${NC}"
	for f in "${failed[@]}"; do
		echo -e "${RED}  ${f##*/}${NC}"
	done
fi

echo ""
echo -e "${GREEN}Done. message audio files saved in $OUTPUT_DIR/${NC}"

# Playback menu. Both arrays hold paths from the same output folder, so sorting
# the combined list needs no external sort: the shell can do it in place
all_files=("${converted[@]}" "${skipped[@]}")
if [[ ${#all_files[@]} -gt 0 ]]; then
	readarray -t all_files < <(printf '%s\n' "${all_files[@]}" | LC_ALL=C sort)
	menu_playback "${all_files[@]}"
fi
