name: Delete Old Workflow Runs

on:
  schedule:
    - cron: '0 0 * * *'  # Run every night at midnight
  workflow_dispatch:     # Allow running manually

jobs:
  delete-old-actions:
    name: Remove old action logs, keeping only most recent 10 logs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yanovation/delete-old-actions@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-latest: 10
          older-than-days: 10        # Remove everything older than 10 days
          keep-minimum-workflows: 10 # Keep at least 5 runs per workflow
          delete-artifacts: true     # Remove related artifacts
