name: Clean

on:
  workflow_dispatch:

jobs:
  delete-old-actions:
    name: Run to remove old action logs, keeping only most recent 5 logs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yanovation/delete-old-actions@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
          keep-latest: 5
