name: Delete Old Workflow Runs

on:
  schedule:
    - cron: '0 0 * * *'  # Run every night at midnight
  workflow_dispatch:     # Allow running manually

permissions:
  actions: write    # Required to remove workflow runs

jobs:
  delete-old-actions:
    name: Remove old action logs, keeping only most recent 10 logs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yanovation/delete-old-actions@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          days-ago: 10        # Remove everything older than 10 days
          keep-latest: 5      # Keep at least 5 runs per workflow
          dry-run: false      # True to test without deleting anything
